name: shipment
description: "shipment app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.9.2+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  geolocator: ^10.1.1
  flutter_osm_plugin: ^1.4.1
  jiffy: ^6.3.1
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  otp_text_field: ^1.1.3
  timer_count_down: ^2.2.2
  http: ^1.2.2
  dropdown_search: ^6.0.1
  multi_dropdown: ^3.0.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.16
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.0
  url_launcher: ^6.3.0
  package_info_plus: ^4.2.0
  easy_stepper: ^0.8.5+1
  flutter_local_notifications: ^18.0.1
  fl_chart: ^0.66.0
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  popover: ^0.2.8+2
  pie_chart: ^5.4.0
  timeago: ^3.7.0
  flutter_image_compress: ^2.4.0
  excel: ^4.0.6
  web_socket_channel: ^3.0.3
  share_plus: ^7.0.2
  flutter_phone_direct_caller: ^2.1.0
#  background_fetch: ^1.3.7
  badges: ^3.1.2
  font_awesome_flutter: ^10.8.0
  flutter_dotenv: ^5.2.1
  app_settings: ^6.0.0
  modal_bottom_sheet: ^3.0.0
  animated_bottom_navigation_bar: ^1.4.0
  video_player: ^2.9.0
  flutter_rating_bar: ^4.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_timer_countdown: ^1.0.7
  webview_flutter: ^4.13.0
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/videos/register_role.mp4
  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-VariableFont_wght.ttf